title: Zjan Turla
sidebar_title: Zjan Turla
description: Hi! I'm Zjan, Software Developer, Software Quality Engineer, and Game Developer.
sidebar_description: Software Engineer focusing on Site Reliability Engineering. </br></br>Previous work revolved around building automated test solutions and improving product development processes. Hobbyist game developer working on a successfully Kickstarted game. </br></br>Other studies and works focus on the intersection of technology and social sciences. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
plugins:
  - jekyll-redirect-from
show_downloads: false
show_playstore: true
show_itunes: true
theme: jekyll-theme-minimal
email: zjancarlo@gmail.com
linkedin: https://linkedin.com/in/zjan-carlo-turla-358b28164
