title: Zjan Turla
tab_title: Zjan Turla | Dev Portfolio
description: Software Developer <br/> Game Developer <br/> Software Quality Engineer <br/> Process Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
show_playstore: true
show_itunes: false
theme: jekyll-theme-minimal
